# Generated by Django 3.1.4 on 2023-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_of_initial_contact',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.AddField(
            model_name='lead',
            name='a_free_copy_of_mastering_the_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='asymmetrique_activity_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='asymmetrique_activity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='asymmetrique_profile_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='asymmetrique_profile_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='digital_advertisement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='get_updates_on_dm_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='how_did_you_hear_about_x_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='i_agree_to_pay_the_amount_through_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_notable_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='magazine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='newspaper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='newspaper_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_views_per_visit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='receive_more_updates_about_our_courses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='through_recommendations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_time_spent_on_website',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_visits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='update_me_on_supply_chain_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='what_is_your_current_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='what_matters_most_to_you_in_choosing_a_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='x_education_forums',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
